### ISSUE TITLE
Multiple monitor drag window

### ISSUE THREAD

**Issue by ghost** [ScreenShottr/ScreenShottr-Java#2]
Drag window only shows on main monitor and not on any additional multiple monitors

**Comment by JeromSar** [comment]
Fixed in https://github.com/ScreenShottr/ScreenShottr-Java/commit/f476e00a9db77af20fa90db089138f1acf9f4ff4

**Comment by Fyrsta** [comment]
This issue isn't completely fixed. You can't take a screenshot of anything on non-primary monitors without starting it on the primary monitor. Also, the screenshot box doesn't extend onto non-primary monitors either.

**Comment by JeromSar** [comment]
@WickedGamingUK can you take a separate screenshot starting and stopping in the non-primary monitor?

**Comment by Fyrsta** [comment]
No, you can't start a screenshot on a non-primary monitor. You can finish the screenshot on the non-primary monitor though, but it needs to start from the primary monitor.
